version: "3.8"
services:
    api:
        image: mamba-backend
        container_name: mamba-backend-container
        build: .
        networks:
            static-network:
                ipv4_address: 172.18.0.2
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.18.0.0/16