name: Deploy tag to Server
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add SSH key
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SERVER_KEY }}
          ssh-host: ${{ secrets.DEPLOY_SERVER_ADDRESS_WITHOUT_SSH }}
      - name: Docker compose build
        run: |
          docker-compose build --no-cache
      - name: Docker deploy image
        run: |
          docker save mamba-backend-vapor_api:latest | docker -H ${{ secrets.DEPLOY_SERVER_ADDRESS }} image load --quiet
      - name: Docker compose container
        env:
          DEPLOY_SERVER_ADDRESS: ${{ secrets.DEPLOY_SERVER_ADDRESS }}
        run: |
          docker-compose -H "${DEPLOY_SERVER_ADDRESS}" down
          docker-compose -H "${DEPLOY_SERVER_ADDRESS}" up -d --force-recreate
