name: Deploy tag to Server
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add SSH key
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SERVER_KEY }}
          ssh-host: ${{ secrets.DEPLOY_SERVER_ADDRESS_WITHOUT_SSH }}
      - name: Docker compose and Deploy to Server
        env:
          DEPLOY_SERVER_ADDRESS: ${{ secrets.DEPLOY_SERVER_ADDRESS }}
        run: |
          docker-compose build --no-cache
          docker save mamba-backend-vapor_api:latest
          docker-compose -H "${DEPLOY_SERVER_ADDRESS}" down
          docker -H "${DEPLOY_SERVER_ADDRESS}" image load
          DOCKER_HOST=${{ secrets.DOCKER_HOST_URL }} docker image load
          docker-compose -H "${DEPLOY_SERVER_ADDRESS}" up -d --force-recreate
